from .role import Role
from .user import User
from .bilkent_courses import BilkentCourses
from .course import Course
from .university import University
from .university_departments import UniversityDepartments
from .todo import Todo
from .applications import Applications
from .faq import Faq 
from .deadlines import Deadlines