from .authenticate_service import AuthenticateService
from .authorize_service import AuthorizeService
from .role_service import RoleService
from .todo_service import TodoService
from .course_service import CourseService
from .applications_service import ApplicationsService
from .deadline_service import DeadlineService
from .faq_service import FaqService
from .pdf_service import PDFService
from .user_service import UserService
from .university_service import UniversityService
from .administrator_service import AdministratorService
from .view_applications_service import ViewApplicationsService
from .final_forms_service import FinalFormsService
from .international_office_service import InternationalOfficeService
from .contacts_service import ContactsService
from .document_strategy import *